### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by JohnUrban** [verznet/OPTIMA#1]
Hi,

Thanks for the tool.

I am currently trying to install and follow instructions from: http://www.davideverzotto.it/research/OPTIMA/

At the moment I am trying to install on Mac OS X.
I downloaded dependencies and sample data/etc:

```
wget http://www.davideverzotto.it/research/OPTIMA/commons-math3-3.2.jar
wget http://www.davideverzotto.it/research/OPTIMA/cern.jar
wget http://www.davideverzotto.it/research/OPTIMA/data/Simulations/Human-scenarioA-KpnI_sample.maps
wget http://www.davideverzotto.it/research/OPTIMA/data/InSilico/Human_reference_hg19-KpnI.silico
wget http://www.davideverzotto.it/research/OPTIMA/data/Simulations/Human-scenarioA-KpnI_sample.locations

```

Then I tried:

```
git clone https://github.com/verznet/OPTIMA.git
javac OPTIMA/Align.java

```

I received a bunch of "does not exist error".. Last line:

```
49 errors
```

Needless to say, this did not work:

```
java OPTIMA.Align Human-scenarioA-KpnI_sample.maps sample_output Human_reference_hg19-KpnI.silico pvalue allMaps > sample_output.log

```

I then tried:

```
git clone https://github.com/verznet/OPTIMA.git
javac -cp ".:cern.jar:commons-math3-3.2.jar" OPTIMA/Align.java
## received no errors
## then tried:
java OPTIMA.Align Human-scenarioA-KpnI_sample.maps sample_output Human_reference_hg19-KpnI.silico pvalue allMaps > sample_output.log

## received this error:
Exception in thread "main" java.lang.NoClassDefFoundError: cern/jet/random/engine/RandomEngine
    at OPTIMA.Align.main(Align.java:44)
Caused by: java.lang.ClassNotFoundException: cern.jet.random.engine.RandomEngine
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more
```

Any suggestions on how to proceed?

Many thanks,

John Urban

**Comment by JohnUrban** [comment]
I just had the same problem trying to install on a Linux-based compute cluster.

Information on the computer cluster OS:

```
$ uname -a
Linux login001 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$
$
$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:    6.7
Codename:   Final
```

Error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: cern/jet/random/engine/RandomEngine
    at OPTIMA.Align.main(Align.java:44)
Caused by: java.lang.ClassNotFoundException: cern.jet.random.engine.RandomEngine
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more
```

**Comment by JohnUrban** [comment]
Thanks for the tip in our e-mail correspondence.

The solution for this issue to run the example for both the Mac OS X and as well as the Linux compute cluster was:

```
java -cp ".:cern.jar:commons-math3-3.2.jar" OPTIMA.Align Human-scenarioA-KpnI_sample.maps sample_output Human_reference_hg19-KpnI.silico pvalue allMaps > sample_output.log
```

The installation and running example worked as:

```
git clone https://github.com/verznet/OPTIMA.git
javac -cp ".:cern.jar:commons-math3-3.2.jar" OPTIMA/Align.java
java -cp ".:cern.jar:commons-math3-3.2.jar" OPTIMA.Align Human-scenarioA-KpnI_sample.maps sample_output Human_reference_hg19-KpnI.silico pvalue allMaps > sample_output.log

```

Other ways, such as not including the `-cp ".:cern.jar:commons-math3-3.2.jar"` in either or both line(s) lead to failure for both Mac OS X and Linux.

**Comment by verznet** [comment]
Thanks a lot John for updating on this!  This might depend on the particular system settings that you are using or on your Java distribution I guess, as typically we run the 'java' command without directly specifying the paths on both our Mac OS X (10.6.8 and 10.9.x) and Linux (CentOS, Ubuntu and Fedora – see https://gist.github.com/philippbayer/c8a6756a1f08345cd746) systems. 

Please let me know if you encounter other issues.  For the usage suggestions, we can revert back to the email correspondence.

Best regards,
Davide
